import { useContext } from "react";

export default function Home() {

    return (
        <>
          <section id="hero" className="d-flex flex-column justify-content-center">
            <div style={{ zIndex: 6 }} className="container aos-init aos-animate">
              <h1>Demo on Nextjs </h1>
            </div>
          </section>
        </>
    );
}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
